[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Optimizer settings for gas efficiency
optimizer = true
optimizer_runs = 200
via_ir = false

# Arc Testnet RPC endpoint
[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"
